# Generated by Django 3.2.6 on 2021-09-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pro_kind',
            field=models.IntegerField(null=True, verbose_name='상품종류'),
        ),
    ]
