# Generated by Django 3.2.6 on 2021-09-06 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=200)),
                ('order_name', models.CharField(max_length=200, verbose_name='받는사람')),
                ('order_tel', models.CharField(max_length=200, verbose_name='연락처')),
                ('order_addr', models.CharField(max_length=200, verbose_name='주소')),
                ('order_status', models.CharField(choices=[('주문완료', '주문완료'), ('결재완료', '결재완료'), ('배송중', '배송중'), ('배송완료', '배송완료'), ('주문취소', '주문취소')], default='주문완료', max_length=20)),
                ('order_date', models.DateField(default=django.utils.timezone.now, verbose_name='주문일')),
                ('delivery', models.CharField(default='', max_length=200, null=True, verbose_name='택배사')),
                ('delivery_no', models.CharField(default='', max_length=200, null=True, verbose_name='송장번호')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_products', to='product.product')),
            ],
        ),
    ]
